// <auto-generated />
namespace WEBSHOP_CKLT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateSubcribe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateSubcribe));
        
        string IMigrationMetadata.Id
        {
            get { return "202312100209137_update Subcribe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
